version: 3.0.{build}
build: false

environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37

install:
  - python -m pip install --ignore-installed -U pip
  - pip install -U virtualenv
  - pip install tox

test_script:
  - tox
